
#
# Copyright (C) 2012 Evgeny Panov
# This file is part of libvrender.
#

SET(CMAKE_SYSTEM_NAME Windows)

set(COMPILER_PREFIX "i586-mingw32msvc")
set(COMPILER_ROOT_PATH /usr/${COMPILER_PREFIX})
#SET(USER_ROOT_PATH /path/to/mingw/)

find_program(CMAKE_RC_COMPILER NAMES ${COMPILER_PREFIX}-windres)
find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-g++)

SET(CMAKE_FIND_ROOT_PATH  ${COMPILER_ROOT_PATH} ${USER_ROOT_PATH})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
